name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+47

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0
  app_links: ^7.0.0
  eitherx: ^2.0.1
  flip_panel_plus: ^1.0.0+3
  get_it: ^9.0.5
  equatable: ^2.0.7
  injectable: ^2.6.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  liquid_pull_to_refresh: ^3.0.1
  syncfusion_flutter_charts: ^31.2.12
  dio: ^5.9.0
  intl: ^0.20.2
  device_info_plus: ^12.2.0
  simple_html_css: ^5.0.0
  responsive_framework: ^1.5.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.9.1
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4
  fcm_config: ^3.6.5
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  flutter_pagewise: ^2.0.4
  package_info_plus: ^9.0.0
  mwidgets: ^1.2.9
  country_code_picker: ^3.4.1
  syncfusion_flutter_datepicker: ^31.2.12
  dotted_line: ^3.2.3
  country_flags: ^4.1.0
  location: ^8.0.1
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  file_picker: ^10.3.6
  percent_indicator: ^4.2.5
  smooth_page_indicator: ^1.2.1
  circular_progress_stack: ^0.0.4
  auto_route: ^10.1.0+1
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  visibility_detector: ^0.4.0+2
  fl_chart: ^1.1.1
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.2.2
  barcode: ^2.2.9
  myfatoorah_flutter: ^3.2.4
  objectbox: ^5.0.2
  objectbox_flutter_libs: ^5.0.2
  web_socket_client: ^0.2.1
  flutter_secure_storage: ^9.2.4
  reorderables: ^0.6.0
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  path_provider: ^2.1.5
  sliver_tools: ^0.2.12
  flutter_slidable: ^4.0.3
  lottie: ^3.3.2
  webview_flutter: ^4.13.0
  auto_size_text: ^3.0.0
  flutter_reaction_button: ^3.0.0+3
  html: ^0.15.6
  flutter_quill: ^11.5.0
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.3
  insta_image_viewer: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  socket_io_client: ^3.1.2
  flutter_native_splash: ^2.4.6
#  clean_architecture_generator:
#    git:
#      url: https://github.com/ibrahimnashat/clean_architecture_generator.git
#      ref: flow_builder
  args: ^2.7.0
  asn1lib: ^1.6.5
  clock: ^1.1.2
  collection: ^1.19.1
  crypto: ^3.0.7
  pointycastle: ^4.0.0
  candle_chart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  auto_route_generator: ^10.2.6
  json_serializable: 6.11.2
  injectable_generator: ^2.9.1
  retrofit_generator: ^10.2.0
  objectbox_generator: ^5.0.2
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/svgs/more/
    - assets/svgs/positions/
    - assets/svgs/chart/
    - assets/jsons/
    - assets/sounds/

  fonts:
    - family: Bank
      fonts:
        - asset: assets/fonts/bank/Bank-Bold.ttf
          weight: 700
        - asset: assets/fonts/bank/Bank-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
